config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :dogs

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete "/signout" => "sessions#destroy"

  get "/profile" => "dogs#profile"

end

app/models/dog.rb
class Dog < ActiveRecord::Base
	has_secure_password
  validates_presence_of :name, :birthday, :city, :state, :email

  validates_uniqueness_of :email

  def birthday?
    birthday.month == Time.now.month && birthday.day == Time.now.day
  end

  def age
    Time.now.year - birthday.year
  end

  def location
    city + ", " + state
  end

  def puppy?
    age < 1
  end

  def age_in_dog_years
    age * 7
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_dog

  def current_dog
    @current_dog ||= Dog.find(session[:dog_id]) if session[:dog_id]
  end


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
  	@dogs = Dog.all
  end

  def new
  	@dog = Dog.new
  end

  def create
  	@dog = Dog.new(dog_params)
  	if @dog.save
  		redirect_to @dog
  	else
  		render 'new'
  	end
  end

  def show
  	@dog = Dog.find(params[:id])
  end

  def profile 
    @dog = current_dog
  end 
  private

  def dog_params
  	params.require(:dog).permit(:name, :email, :password, :city, :state, :birthday, :newsletter)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@dog = Dog.find_by_email(params[:email])
  	if @dog && @dog.authenticate(params[:password])
  		session[:dog_id] = @dog.id	
  		flash[:notice] = "Walked in the doggy door successfully."
  		redirect_to @dog
  	else
  		flash[:alert] = "There was a problem, dog."
  		render 'new'
  	end
  end

  def destroy
    session[:dog_id] = nil
    flash[:notice] = "You've been signed out, dog."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dogs/index.html.erb
<h1>All Dogs</h1>
<% @dogs.each do |dog| %>
	<%= dog.name %>
<% end %>

app/views/dogs/new.html.erb
<h1>New Dog Form</h1>
<%= form_for @dog do |d| %>
	<%= d.label :name %>
	<%= d.text_field :name %>
	<%= d.label :email %>
	<%= d.text_field :email %>
	<%= d.label :password %>
	<%= d.password_field :password %>
	<%= d.label :birthday %>
	<%= d.date_select :birthday %>	
	<%= d.label :city %>
	<%= d.text_field :city %>
	<%= d.label :state %>
	<%= d.text_field :state %>
	<%= d.label :newsletter %>
	<%= d.check_box :newsletter %>

	<%= d.submit %>
<% end %>

app/views/dogs/profile.html.erb
<h1>Welcome, <%=@dog.name%></h1>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

app/views/home/index.html.erb
<h1>Welcome to the Doghouse</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
	<ul>
	<% if current_dog %>
		<li>
			<%=link_to "My Profile", profile_path %>
		</li>
		<li>
			<%=link_to "Log Out", signout_path, method: :delete %>
		</li>
	<% else %>
		<li>
      <%=link_to "Sign In", signin_path %>
    </li>
    <li>
      <%=link_to "Sign Up", new_dog_path %>
    </li>
   <% end %>
	</ul>
</nav>

<%= yield %>

</body>
</html>